export const GET_TASKS_FULFILLED = 'GET_TASKS_FULFILLED';
export const ADD_TASK_FULFILLED = 'ADD_TASK_FULFILLED';
export const DELETE_TASK_FULFILLED = 'DELETE_TASK_FULFILLED';
export const EDIT_TASK_FULFILLED = 'EDIT_TASK_FULFILLED';
