export const GET_TIMESHEETS_SUCCESS = 'GET_TIMESHEETS_SUCCESS';
export const ADD_TIMESHEETS_SUCCESS = 'ADD_TIMESHEETS_SUCCESS';
export const DELETE_TIMESHEETS_SUCCESS = 'DELETE_TIMESHEETS_SUCCESS';
export const EDIT_TIMESHEETS_SUCCESS = 'EDIT_TIMESHEETS_SUCCESS';
export const TIMESHEETS_PENDING = 'TIMESHEETS_PENDING';
export const TIMESHEETS_ERROR = 'TIMESHEETS_ERROR';
