export const GET_SUPERADMINS_FULFILLED = 'GET_SUPERADMINS_FULFILLED';
export const ADD_SUPERADMINS_FULFILLED = 'ADD_SUPERADMINS_FULFILLED';
export const DELETE_SUPERADMINS_FULFILLED = 'DELETE_SUPERADMINS_FULFILLED';
export const EDIT_SUPERADMINS_FULFILLED = 'EDIT_SUPERADMINS_FULFILLED';
