export const GET_MEMBERS_SUCCESS = 'GET_MEMBERS_SUCCESS';
export const ADD_MEMBERS_SUCCESS = 'ADD_MEMBERS_SUCCESS';
export const DELETE_MEMBERS_SUCCESS = 'DELETE_MEMBERS_SUCCESS';
export const EDIT_MEMBERS_SUCCESS = 'EDIT_MEMBERS_SUCCESS';
export const MEMBERS_PENDING = 'MEMBERS_PENDING';
export const MEMBERS_ERROR = 'MEMBERS_ERROR';
