export const SET_USER = 'SET_USER';

export const GET_EMPLOYEE_PENDING = 'GET_EMPLOYEE_PENDING';
export const GET_EMPLOYEE_SUCCESS = 'GET_EMPLOYEE_SUCCESS';
export const GET_EMPLOYEE_ERROR = 'GET_EMPLOYEE_ERROR';
